name: Deploy to SFTP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codea
        uses: actions/checkout@v2

      - name: Setup SFTP
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          local: './'
          remote: '/chronica/txData/QBCoreFramework_BA9C00.base/resources/selim-drifts'
