name: Deploy via ftp
on: push
jobs:
  web-deploy:
    name: 🚀 Deploy the Script Every Commit
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get Latest Code
      uses: actions/checkout@v3
    
    - name: 📂 Sync Files
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: ${{ secrets.FTP_HOST }}
        remote-user: ${{ secrets.FTP_USERNAME }}
        private-ssh-key: ${{ secrets.SSH_KEY }}
        destination-path: /chronica/txData/QBCoreFramework_BA9C00.base/resources/selim-drifts
        ssh-port : ${{ secrets.FTP_PORT }}
