            - name: ftp-action
  # You may pin to the exact commit or the version.
  # uses: sebastianpopp/ftp-action@eb75c5cb29d23ee4a729720a27dfb66403cb0f6d
  uses: sebastianpopp/ftp-action@v2.0.0
  with:
    # FTP host
    host: chronicarp.fr:49152
    # FTP user
    user: root
    # FTP password
    password: 
    # Force SSL encryption
    forceSsl: true# optional, default is false
    # Local directory
    localDir: # optional, default is .
    # Remote directory
    remoteDir: /chronica/txData/QBCoreFramework_BA9C00.base/resources/selim-drifts # optional, default is .
          
